COMPONENT=BeaconAppC
CFLAGS += -I$(TOSDIR)/lib/net \
          -I$(TOSDIR)/lib/net/le \
          -I$(TOSDIR)/lib/net/ctp \
          -I$(TOSDIR)/lib/net/drip \
          -I ../
MSG_SIZE = 114
include $(MAKERULES)
