COMPONENT=BikeAppC
SENSORBOARD=mts420cc
CFLAGS += -I$(TOSDIR)/lib/net \
          -I$(TOSDIR)/lib/net/le \
          -I$(TOSDIR)/lib/net/ctp \
          -I$(TOSDIR)/lib/net/drip \
          -I ../ \
          -I ../mts420cc/
MSG_SIZE = 114
include $(MAKERULES)
